system:
  name: "SYMBEON"
  version: "1.0.0"
  environment: "development"
monitoring:
  metrics:
    collection_interval: 60
    retention_days: 30
    error_threshold: 3
  health:
    check_interval: 30
    history_size: 1000
    critical_threshold: 0.8
integration:
  eon_framework:
    mode: "symbiotic"
    cache_enabled: true
    distributed: true
  vireon:
    meta_governance: true
    adaptation_rate: 0.15
    validation_threshold: 0.95
